### ISSUE TITLE
Unauthorized trying to place Buy order

### ISSUE THREAD

**Issue by Drag0s** [pladaria/degiro#13]
Hello all,

When trying to place a buy order, I get a `FetchError`

**Log before sending request**:
```javascript
checkOrder { buysell: 0,
  orderType: 2,
  productId: '121041',
  size: '1',
  timeType: 3,
  price: undefined,
  stopPrice: undefined }
```

**FetchError**
```javascript
{ Error
    at /*deleted*/node_modules/node-fetch/lib/body.js:48:31
    at propagateAslWrapper (/*deleted*/node_modules/async-listener/index.js:468:23)
    at /*deleted*/node_modules/async-listener/index.js:505:70
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'FetchError',
  message: 'invalid json response body at https://trader.degiro.nl/trading_s/secure/v5/checkOrder;jsessionid=*deleted*.prod5?intAccount=*deleted*&sessionId=*deleted*.prod5 reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
```

Intercepting the HTTP request from DeGiro, I have the following response:

**DeGiro response**
```html
<html>
<head>
<title>Apache Tomcat/7.0.64 - Error report</title>
<style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style>
</head>
<body>
<h1>HTTP Status 401 - Unauthorized AuthenticationCredentialsNotFoundException</h1>
<HR size="1" noshade="noshade">
<p><b>type</b> Status report</p>
<p><b>message</b> <u>Unauthorized AuthenticationCredentialsNotFoundException</u></p>
<p><b>description</b> <u>This request requires HTTP authentication.</u></p>
<HR size="1" noshade="noshade">
<h3>Apache Tomcat/7.0.64</h3>
</body>
</html>
``` 

Thanks!

**Comment by Drag0s** [comment]
I've found the problem.

Seems like the `checkOrder` and `confirmOrder` endpoints are using the `/trading/secure/v5/order...` route instead of the `/trading_s/secure/v5/order...` one.
