### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by marianowicz** [pladaria/degiro#2]
Hi
  Login worked successfully until most recent Monday (2017-06-05). Then I installed Degiro mobile client and set pincode. After that login stopped working. So I thought these two things were related and created a new Degiro account with a new username and password (since it was impossible to restore a previous way of logging in for my first account). Surprisingly the problem persists, so I cannot log in to any of my accounts using this package.

An exception that is thrown says
`
Error: Login error
    at fetch.then.res (/home/mysusername/www/myappname/js/node_modules/degiro/src/index.js:112:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
`

Full Degiro response is:
```
Body {
  url: 'https://trader.degiro.nl/login/securityCheck',
  status: 302,
  statusText: 'Found',
  headers: 
   Headers {
     _headers: 
      { date: [Object],
        'content-type': [Object],
        'content-length': [Object],
        connection: [Object],
        'strict-transport-security': [Object],
        location: [Object],
        'cache-control': [Object],
        pragma: [Object],
        expires: [Object],
        'x-zen-fury': [Object],
        server: [Object] } },
  ok: false,
  body: 
   PassThrough {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: true,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: true,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: { end: [Object] },
     _eventsCount: 1,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _transformState: 
      TransformState {
        afterTransform: [Function],
        needTransform: false,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: null } },
  bodyUsed: false,
  size: 0,
  timeout: 0,
  _raw: [],
  _abort: false }
```

where headers section is:
```
Headers {
  _headers: 
   { date: [ 'Thu, 08 Jun 2017 10:04:17 GMT' ],
     'content-type': [ 'text/html' ],
     'content-length': [ '0' ],
     connection: [ 'close' ],
     'strict-transport-security': [ 'max-age=315360000; includeSubDomains' ],
     location: [ 'https://trader.degiro.nl/login/login_error' ],
     'cache-control': [ 'no-cache, no-store, must-revalidate' ],
     pragma: [ 'no-cache' ],
     expires: [ '0' ],
     'x-zen-fury': [ 'some long string is here, I do not know if this is private data or not so I do not put it here' ],
     server: [ 'ZENEDGE' ] } }
```

Any idea how to fix it? Of course password is correct.

**Comment by Sire** [comment]
The login call changed two days ago. The URL is now /login/secure/login
and you must now POST a json similar to this:
{"username":"abc","password":"xxx","isRedirectToMobile":false,"loginButtonUniversal":"","queryParams":{"reason":"session_expired"}}
Turn on development mode in Chrome (F12), click persist login and do a login on the web site. You will see the request you need to emulate. You will need to mark the POST as content-type json as well.

I only use source code as reference so I can't show you the entire implementation I'm afraid.

**Comment by marianowicz** [comment]
Thank you very much! I will try out your solution :)

**Comment by marianowicz** [comment]
Works like a charm :) Full implementation below:

```
    /**
     * Login
     *
     * @return {Promise} Resolves to {sessionId: string}
     */
    const login = () => {
        log('login', username, '********');
        return fetch(`${BASE_URL}/login/secure/login`, {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({
                "username": username,
                "password": password,
                "isRedirectToMobile": false,
                "loginButtonUniversal": "",
                "queryParams": {"reason": "session_expired"}
            })
        })
        .then(res => {
            const cookies = parseCookies(res.headers.get('set-cookie') || '');
            session.id = cookies.JSESSIONID;
            if (!session.id) {
                throw Error('Login error');
            }
        })
        .then(updateClientInfo)
        .then(() => session);
    };
```

Thanks!

**Comment by pladaria** [comment]
PRs are welcome :)

**Comment by martijndierckx** [comment]
I created a pull request for this

**Comment by pladaria** [comment]
Thank you! v1.0.1 published
