### ISSUE TITLE
search-product.js is not working for me

### ISSUE THREAD

**Issue by sbru** [pladaria/degiro#20]
Dear pladaria
Thank you for creating the DeGiro API.

It works for me, please delete the issue.

**Comment by sbru** [comment]
The search-product script is working after replacing all the files to the new version

But Sell is still not working.

{ FetchError: invalid json response body at https://trader.degiro.nl/trading_s/secure/v5/checkOrder;jsessionid=xxx.prod5?intAccount=xxx&sessionId=xxx.prod5 reason: Unexpected token < in JSON at position 0
    at /Users/xx/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'FetchError',
  message: 'invalid json response body at https://trader.degiro.nl/trading_s/secure/v5/checkOrder;jsessionid=2xxxx.prod5?intAccount=xxxx&sessionId=xxx.prod5 reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
