### ISSUE TITLE
getAskBidPrice() failing for certain products

### ISSUE THREAD

**Issue by d99kris** [pladaria/degiro#22]
I'm not sure it's an issue with the JS API or the actual degiro service. But when requesting bid prices for certain products it fails. For example using the example and changing the id to '6365435' the following error is presented:

> $ DEGIRO_USER=XXX DEGIRO_PASS=YYY node examples/ask-bid-price.js
> Error: Couldn't find all requested info: [{"m":"d","v":["6365435.BidPrice","Record not found in subscription"]},{"m":"d","v":["6365435.AskPrice","Record not found in subscription"]},{"m":"d","v":["6365435.LastPrice","Record not found in subscription"]},{"m":"d","v":["6365435.LastTime","Record not found in subscription"]}]
>     at Error (native)
>     at checkData (/home/ZZZ/src/index.js:140:27)
>     at process._tickCallback (internal/process/next_tick.js:109:7)

The actual copy of `ask-bid-price.js` used to reproduce the problem has been attached as [ask-bid-price.js.txt](https://github.com/pladaria/degiro/files/1314507/ask-bid-price.js.txt).

It should be added that the original example (product id 350009261) does work for me.

**Comment by d99kris** [comment]
This is not really an issue for my app, so I will close this. If someone at some point figures out more specifically if there's something wrong with this API implementation, I think a new issue can be created.
