### ISSUE TITLE
deleteOrder Help

### ISSUE THREAD

**Issue by onofff** [pladaria/degiro#33]
Hello, can someone give me a hint how to use the deleteOrder Function?

Already Try:

```
 degiro.login().then(degiro.deleteOrder({orderID:

 'f90104d9-d8f1-4383-9125-ee37026f0697'}))
.then(console.log)
.catch(console.error);
```

but returns an error:

```
/index.js:350
                body: JSON.stringify(order),
                                     ^

ReferenceError: order is not defined
    at Object.deleteOrder (/var/www/html/degiro/src/index.js:350:38)
    at Object.<anonymous> (/var/www/html/gcash.js:4:28)
'

```

**Comment by HerrSubset** [comment]
Which version are you using? For me it seems to work with version 3.0.1. I'm getting an error about the the delete order failing, but that's because I used the order id you have in your code snippet.

code:
```javascript
const DeGiro = require('..');

 const degiro = DeGiro.create({
   //     username: 'john',
   //     password: 'password',
});

degiro.login()
    .then(() => {
        degiro
            .deleteOrder({orderID: 'f90104d9-d8f1-4383-9125-ee37026f0697'})     
            .then(console.log)
            .catch(console.error);
    })
    .then(console.log)
    .catch(console.error);

```

output:
```
undefined
Error: Delete order failed
    at /home/pyjamas/Projects/degiro/src/index.js:378:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

```

**Comment by cbarbu** [comment]
I also have troubles with deleteOrder. @HerrSubset if I copy paste your code in examples/deleteOrder.js (putting my login/password and a known orderId of mine), then I get like you: 

`node examples/deleteOrder.js`
> undefined
> Error: Delete order failed
>     at Error (native)
>     at /home/cbarbu/Documents/perso/finances/node_modules/degiro/src/index.js:379:27
>     at process._tickCallback (internal/process/next_tick.js:109:7)

Other examples in the examples/ folder work fine. I use degiro@3.1.0 according to package.json and node v6.14.1.

**Comment by HerrSubset** [comment]
But you do have orders defined that can be deleted?

This error is thrown [on purpose](https://github.com/pladaria/degiro/blob/master/src/index.js#L379), so it might be that Degiro updated their website and made the code outdated. I haven't looked into it yet.

**Comment by cbarbu** [comment]
Yes I did have an order defined.

**Comment by icastillejogomez** [comment]
Try this module: https://www.npmjs.com/package/degiro-api
