### ISSUE TITLE
Only absolute URLs are supported

### ISSUE THREAD

**Issue by EtienneHeyman** [pladaria/degiro#49]
Thanks for this tutorial. I have some troubles if I try to buy actions with the API : 
I'm using it on raspbian. 

`const DeGiro = require('..');

const degiro = DeGiro.create({username: 'mylogin', password: 'mypassword'});

degiro
    .setOrder({
        buySell: DeGiro.Actions.buy,
        orderType: DeGiro.OrderTypes.marketOrder,
        productId: '8066561'',
        size: 1,
    })
    .then(console.log); 
`

This is the answer on the terminal : 
pi@raspberrypi:~/degiro/examples $ node buy.js
(node:18927) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Only absolute URLs are supported
(node:18927) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

If I change the program to put the username and password in the command line of the terminal I got this : 

checkOrder { buySell: 'BUY',
  orderType: 2,
  productId: '8066561',
  size: 1,
  timeType: 1,
  price: undefined,
  stopPrice: undefined }
{ id: undefined, account: NaN, userToken: null, clientInfo: null }
(node:19088) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Only absolute URLs are supported
(node:19088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

With some other programs, it's working fine : (for example ask-bid-price.js or search-product.js, etc)

Thanks in advance for your help.

**Comment by bakwan79** [comment]
Hello, Have you used the login function ? create doesn't log you in. I'm you to Node and didn't know about asynchronous programming so I got the same error by trying to use a function before I was logged. I went through it with something like this 
degiro.login().then(degiro.getCashFunds())

**Comment by EtienneHeyman** [comment]
Hi bakwan79,

Thanks a lot for your help :) 
**I've tried this program :** 



`const DeGiro = require('..');

// Set your username and password below or run from terminal as:
// DEGIRO_USER=username DEGIRO_PASS=password node examples/buy.js

const degiro = DeGiro.create({username: ‘mylogin', password: ‘mypassword'});


degiro.login().then(degiro.setOrder({
        buySell: DeGiro.Actions.buy,
        orderType: DeGiro.OrderTypes.marketOrder,
        productId: '8066561',
        size: 1,
    })
)

    .then(console.log)
    .catch(console.error);
`

**The terminal answers :** 

pi@raspberrypi:~/degiro/examples $ nodejs myprogram.js
(node:24042) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/pi/node_modules/node-fetch/lib/index.js:1293:9)
    at /home/pi/node_modules/node-fetch/lib/index.js:1393:19
    at new Promise (<anonymous>)
    at fetch (/home/pi/node_modules/node-fetch/lib/index.js:1390:9)
    at checkOrder (/home/pi/degiro/src/index.js:408:16)
    at Object.setOrder (/home/pi/degiro/src/index.js:459:9)
    at Object.<anonymous> (/home/pi/degiro/examples/myprogram.js:9:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
(node:24042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24042) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 


After this, the terminal shows my private data of Degiro (As the login function alone)


degiro.getCashFunds() and degiro.login() are working fine with me. that's why I try with the buying function. May be you have a little example ?

**Comment by bakwan79** [comment]
I'm sorry, I've not tried this so far, I'll let you know if I manage to get this work

**Comment by EtienneHeyman** [comment]
ok I will try another method this week, I let you know. Thanks for your help.

**Comment by bakwan79** [comment]
ok cool, can you update on what was the problem, because your code seems ok

**Comment by marcobazzani** [comment]
it's not working for me with the same error

**Comment by marcobazzani** [comment]
solved, wasn't waiting for the login to complete

**Comment by allenwixted** [comment]
Same issue happening for me with the basic get portfolio example. 

Originally worked fine

**Comment by icastillejogomez** [comment]
Try this module: https://www.npmjs.com/package/degiro-api
