### ISSUE TITLE
Error Placing Order

### ISSUE THREAD

**Issue by onofff** [pladaria/degiro#64]
Since last thursday i am not able to place orders with function setOrder().
Anyone else with same issue?
Error bellow:

Error
    at checkSuccess (/var/www/html/degiro/src/index.js:41:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

Thanks in advance.

**Comment by delphinbock** [comment]
I've the same issue since last thursday.
No possible setOrder()

**Comment by oscarmoutinho** [comment]
Response data inside setOrder (checkOrder and confirmOrder) has changed.
confirmationId -> data.confirmationId
orderId -> data.orderId

**Comment by onofff** [comment]
Hello, thanks for the help.
I updated lines:

`422 - .then(json => ({order, confirmationId: json.data.confirmationId}));`
`446 - .then(json => ({orderId: json.data.orderId}));`

however i am still getting same error.
Thank you,

**Comment by oscarmoutinho** [comment]
Check 'checkSuccess'.
'status' no longer exists if OK.
I wrote myself an alternative code so I do not use 'checkSuccess'.
I think, now, 'checkSuccess' should be different for different calls.

**Comment by oscarmoutinho** [comment]
JSON sample from checkOrder:
{
    "data": {
        "confirmationId": "54221082-5484-4a7c-84d6-3c7bd0d4c131",
        "transactionFees": [
            {
                "id": 2,
                "amount": 0.02,
                "currency": "USD"
            },
            {
                "id": 3,
                "amount": 0.5,
                "currency": "EUR"
            }
        ]
    }
}

JSON sample from confirmOrder:
{
    "data": {
        "orderId": "63013d7c-6219-4b53-9a5b-c060e8f2f0fc"
    }
}

**Comment by cbarbu** [comment]
Same issue here, any chance this would be made a pull request ?

**Comment by onofff** [comment]
Any one working on the pull request? was anyone able to solve the issue yet?

**Comment by oscarmoutinho** [comment]
I'm not used to github :(

**Comment by cbarbu** [comment]
@oscarmontinho, if you copy paste the text of the modified files (specifying the files where it is) I will gladly do the pull requests (I'm not good at js but do git all day).

**Comment by oscarmoutinho** [comment]
This shoulkd work.

As onofff proposed:
422 - .then(json => ({order, confirmationId: json.data.confirmationId}));
446 - .then(json => ({orderId: json.data.orderId}));

Then: (40, 41, 42)
  original:
        if (res.status !== 0) {
            throw Error(res.message);
        }
   change to:
 	if (res.errors !== undefined && res.errors !== null) {
		throw Error(res.errors[0].text);
	}

**Comment by cbarbu** [comment]
Thanks @oscarmoutinho. This fixed it for me and I'm creating the pull request.

**Comment by cbarbu** [comment]
I sent the pull request and you can get the fixed thing on my repo as referenced above.

**Comment by faerietree** [comment]
It seems DeGiro|vwdServices changed again. Maybe new restrictions?

**Comment by oscarmoutinho** [comment]
Friday was fine. What did you detect and when ?

A domingo, 1 de set de 2019, 14:30, J.R.I. <notifications@github.com>
escreveu:

**Comment by faerietree** [comment]
Thank you for your answer Oscar. To me either no more data responses arrive.
Apart from that there is "Key not in subscription" error communicated by VWDservices when fetching prices. Which is strange because I have realtime data subscription.
`ask-bid-price.js` example also fails with "missing data".
Any possibility DeGiro serves different versions to different countries? Maybe I should tunnel via France or Nederlands and check again..

**Comment by oscarmoutinho** [comment]
But that was friday ?!

J.R.I. <notifications@github.com> escreveu no dia domingo, 1/09/2019 à(s)
15:12:

**Comment by faerietree** [comment]
No worries. I will find a way to fetch prices another way. How do you fetch prices then?

**Comment by oscarmoutinho** [comment]
I use https://www.alphavantage.co/  for almost everything.
I just use DEGIRO for trading.

J.R.I. <notifications@github.com> escreveu no dia domingo, 1/09/2019 à(s)
15:30:

**Comment by faerietree** [comment]
Thank you for sharing, Sir! And as said: don't worry.
Is alpha vantage of advantage? Is it less delayed?

**Comment by oscarmoutinho** [comment]
I don't understand: "Is alpha vantage of advantage? Is it less delayed?"
What do you mean ?
If you are asking if the response values are delayed, I think they are not.

This is undocumented and gets current quotes: (symbols example:
'INTL,GOOG,FB')
'https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES&symbols=' +
symbols + '&apikey=' + KEY;

J.R.I. <notifications@github.com> escreveu no dia domingo, 1/09/2019 à(s)
23:09:

**Comment by 8-j** [comment]
@oscarmoutinho Thank you very much.
Do you know what vwdservices CORS has to do? It does no longer work for me. Thus no ask bid prices. The response is just {"m":"sr"}.
Is the vwdSession required for placing orders?

**Comment by 8-j** [comment]
It is virtually impossible to get most recent quote for XETRA other than via degiro quotecast it seems :-|

**Comment by oscarmoutinho** [comment]
I have no issues using the APIs.
One possible DEGIRO bug in the last days: 2 complete transactions only show
completed after end of day (?!)

Jan <notifications@github.com> escreveu no dia sexta, 18/10/2019 à(s) 16:14:

**Comment by 8-j** [comment]
And suddenly it works again. Likely an outage at VWD quotecast. Thanks for your answer. I will have an eye on the transaction anomaly.

**Comment by 8-j** [comment]
Unfortunately as long as there is no alternative way to get realtime XETRA stock quotes, it is very very risky - should such outages ever happen again. Usually Murphy's Law will make it appear when it is not desirable at all. ;-)

**Comment by icastillejogomez** [comment]
Try this module: https://www.npmjs.com/package/degiro-api
