### ISSUE TITLE
Could not finish a test buy. 

### ISSUE THREAD

**Issue by Behnam-Nouri** [pladaria/degiro#68]
I tried a limited order with Google Apple or SAP. All 3 failed.
But i cant find out why. Login, cashfund etc all works fine.

Error
    at checkSuccess (/home/XXX/degiro-api/js/node_modules/degiro/src/index.js:41:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Is this because of degiro?

**Comment by jensdenbraber** [comment]
Same problem here :(

**Comment by icastillejogomez** [comment]
Try this module: https://www.npmjs.com/package/degiro-api
