### ISSUE TITLE
syntax Error Index.js:21

### ISSUE THREAD

**Issue by wesmoen** [pladaria/degiro#7]
Hi guys, 

So far, I really like your work, but when I want to run a test script. I get this message

C:\Users\Wesmoen\node_modules\degiro\src\index.js:21
) => {
^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Wesmoen\node_modules\degiro\examples\login.js:1:78)

Removing the comma on rule 20, will kind of fix it. But I'm sure I'd doing more wrong than right.

Specs:
Node v6.11.1
NPM v5.3.0
Windows 10 Pro

I went to look in older commits, but I have the idea that I'm missing something on my PC. 

Thank you for your time,
Wesmoen

**Comment by wesmoen** [comment]
Apparently, The syntax got changed in Node JS v8. Perhaps a good idea to put in the Readme which version is necessary to make your code work. 

But it is fixed now.
