### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by sunkaflek** [pladaria/degiro#70]
Hi
I'm having trouble with even the most basic command - logging in:

`const DeGiro = require('degiro');
const degiro = DeGiro.create({username: 'xxx', password: 'xxx'});
degiro.login().then(session => console.log(session));`

This yields:

> UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/nnn/degiro-api/node_modules/node-fetch/lib/index.js:1299:9)
    at /Users/nnn/degiro-api/node_modules/node-fetch/lib/index.js:1404:19
    at new Promise (<anonymous>)
    at fetch (/Users/nnn/degiro-api/node_modules/node-fetch/lib/index.js:1401:9)
    at getClientInfo (/Users/nnn/degiro-api/node_modules/degiro/src/index.js:250:9)

What baffles me is that the same code seemed to work just few days ago. Any ideas?

**Comment by sunkaflek** [comment]
I think I figured it out, now working for me. I had to change this (adding the "data."):

`    /**
     * Get config
     *
     * @return {Promise}
     */
    const updateConfig = () =>
        fetch(`${BASE_TRADER_URL}/login/secure/config`, {
            headers: {Cookie: `JSESSIONID=${session.id};`},
        })
            .then(res => res.json())
            .then(res => {
                urls.paUrl = res.data.paUrl;
                urls.productSearchUrl = res.data.productSearchUrl;
                urls.productTypesUrl = res.data.productTypesUrl;
                urls.reportingUrl = res.data.reportingUrl;
                urls.tradingUrl = res.data.tradingUrl;
                urls.vwdQuotecastServiceUrl = res.data.vwdQuotecastServiceUrl;
            });`

**Comment by kraag22** [comment]
can you create PR for it?

**Comment by sunkaflek** [comment]
> can you create PR for it?

yes: https://github.com/pladaria/degiro/pull/71

**Comment by icastillejogomez** [comment]
Try this module: https://www.npmjs.com/package/degiro-api
