### ISSUE TITLE
new unknown error

### ISSUE THREAD

**Issue by aravindnadumane** [pladaria/degiro#74]
I once downloaded this source and tested it some months back. Worked like a gem. But today I wanted to further start on automatic but all of a sudden i'm get stumbled. What is this Error.
I uninstalled degiro and reinstalled, but it is stubborn. Please help me if this is compatible with the latest Degiro changes ?

` node get-client-info.js
(node:6252) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Garage\Scripting\node\node_modules\node-fetch\lib\index.js:1299:9)
    at C:\Garage\Scripting\node\node_modules\node-fetch\lib\index.js:1404:19
    at new Promise (<anonymous>)
    at fetch (C:\Garage\Scripting\node\node_modules\node-fetch\lib\index.js:1401:9)
    at getClientInfo (C:\Garage\Scripting\node\node_modules\degiro\src\index.js:250:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asy
nc function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on u
nhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_reje
ctions_mode). (rejection id: 2)
(node:6252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are no
t handled will terminate the Node.js process with a non-zero exit code.`

**Comment by icastillejogomez** [comment]
This repo is dead. Did you tried https://www.npmjs.com/package/degiro-api ?

**Comment by aravindnadumane** [comment]
This I tried already and I get unknown error.

`$ node get-portfolio.js
C:\Garage\Scripting\node\degiro-api_module\get-portfolio.js:1
import DeGiro, { DeGiroEnums, DeGiroTypes } from 'degiro-api'
^^^^^^

SyntaxError: Cannot use import statement outside a module
?[90m    at wrapSafe (internal/modules/cjs/loader.js:1072:16)?[39m
`
I installed it as described in your page and i see that it is installed in my setup
`$ npm -g ls
C:\Users\arso271062\AppData\Roaming\npm
`-- degiro-api@0.5.2
  +-- async@3.2.0
  `-- node-fetch@2.6.0
`

my get-portfolio.js contains the source from your site:
`import DeGiro, { DeGiroEnums, DeGiroTypes } from 'degiro-api'
const { PORTFOLIO_POSITIONS_TYPE_ENUM } = DeGiroEnums
 
(async () => {
 
  const degiro: DeGiro = new DeGiro({
    username: 'nadumane',
    pwd: 'dearJockey-007',
  })
 
  await degiro.login()
 
  const portfolio = await degiro.getPortfolio({ type: PORTFOLIO_POSITIONS_TYPE_ENUM.ALL })
  console.log(JSON.stringify(portfolio, null, 2))
})()`

Please help me what i'm wrong. I'm from Perl bash background and the node enviroment is quite new for me. perhaps I'm using it wrong. I have the git bash for windows environment.

**Comment by icastillejogomez** [comment]
Post in the correct repository: https://github.com/icastillejogomez/degiro-api/issues

**Comment by aravindnadumane** [comment]
Thanks for the Hint. I have opened a issue there. Please help me
